# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeleteorder():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deleteorder(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1296, 688)
    self.vars["product_name"] = "Iphone 6 32gb"
    self.driver.find_element(By.LINK_TEXT, "self.vars["product_name"]").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    assert self.driver.switch_to.alert.text == "Product added"
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//td[contains(.,\'self.vars["product_name"]\')]")))
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'self.vars["product_name"]\')]")
    assert len(elements) == 0
    self.driver.close()
  
