# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPassorder():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_passorder(self):
    self.driver.get("https://www.demoblaze.com/")
    self.vars["product_name"] = "Samsung galaxy s6"
    self.driver.set_window_size(654, 672)
    self.driver.find_element(By.LINK_TEXT, "self.vars["product_name"]").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    assert self.driver.switch_to.alert.text == "Product added"
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.XPATH, "//td[contains(.,\'self.vars["product_name"]\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".success:nth-child(1) > td:nth-child(2)").click()
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'self.vars["product_name"]\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".success:nth-child(1) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Nessma Hamidou")
    self.driver.find_element(By.ID, "country").send_keys("Tunisie")
    self.driver.find_element(By.ID, "city").send_keys("Tunis, Tunisia")
    self.driver.find_element(By.ID, "card").click()
    self.driver.find_element(By.ID, "card").send_keys("1234444")
    self.driver.find_element(By.ID, "month").click()
    self.driver.find_element(By.ID, "month").click()
    element = self.driver.find_element(By.ID, "month")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "month").send_keys("12")
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys("2024")
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .modal-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
    elements = self.driver.find_elements(By.XPATH, "//td[contains(.,\'self.vars["product_name"]\')]")
    assert len(elements) == 0
    elements = self.driver.find_elements(By.ID, "totalp")
    assert len(elements) == 0
    self.driver.close()
  
